eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
server:
  port: 8090
spring:
  application:
    name: wecommerce
    configuration :
      user-url : http://localhost:8070/api/v1/users
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wecommerce
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
